import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const { name, email, contact, price, courseName } = await req.json();

    if (!name || !email || !contact || !courseName) {
      return Response.json({ message: "Missing fields" }, { status: 400 });
    }

    // Transporter
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
    });

    const html = `
 <div style="
    width: 100%;
    padding: 0px;
    background: #F4F4F7;
    font-family: Arial, sans-serif;
  ">
    <div style="
      max-width: 600px;
      margin: auto;
      background: #ffffff;
      border-radius: 14px;
      padding: 30px;
      border: 1px solid #e6e6e6;
      box-shadow: 0 6px 25px rgba(0,0,0,0.08);
    ">
      
      <div style="text-align:center; margin-bottom: 25px;">
        <img src="https://inframeschool.com/pixelcut-export4.png" width="120" style="margin-bottom:10px;" />
        
        <h2 style="
          color: #222;
          margin-bottom: 10px;
          font-size: 26px;
        ">
          🎉 New Student Enrollment Lead
        </h2>
        
        <p style="color:#666; font-size:14px; margin:0;">
          A student has shown interest in purchasing a course.
        </p>
      </div>

      <div style="
        background: #fafafa;
        padding: 18px 20px;
        border-radius: 10px;
        border: 1px solid #eee;
        margin-bottom: 20px;
      ">
        <p style="font-size:16px; color:#333; margin:8px 0;">
          <strong>Name:</strong> ${name}
        </p>
        <p style="font-size:16px; color:#333; margin:8px 0;">
          <strong>Email:</strong> ${email}
        </p>
        <p style="font-size:16px; color:#333; margin:8px 0;">
          <strong>Phone:</strong> ${contact}
        </p>
        <p style="font-size:16px; color:#333; margin:8px 0;">
          <strong>Course Name:</strong> ${courseName}
        </p>
        <p style="font-size:16px; color:#333; margin:3px 0;">
          <strong>Price:</strong>
          <span style="color:#0A8A0A; font-weight:700;">₹${price}</span>
        </p>
      </div>

      <div style="text-align:center; margin: 30px 0;">
        <a href="tel:+919971126661"
          style="
            background: linear-gradient(90deg, #FACC15, #EAB308);
            padding: 14px 28px;
            color: #000;
            font-size: 18px;
            border-radius: 30px;
            text-decoration: none;
            font-weight: bold;
            display: inline-block;
            box-shadow: 0 3px 12px rgba(250, 204, 21, 0.4);
          "
        >
          📞 Call Student Now
        </a>
        <p style="color:#777; font-size:13px; margin-top:10px;">
          Contact the student to assist with the enrollment.
        </p>
      </div>

      <hr style="border:none; border-top:1px solid #eee; margin:25px 0;">

      <p style="text-align:center; font-size:13px; color:#777;">
        This lead alert was generated by <strong>Inframe College</strong>.
      </p>
    </div>
  </div>
`;

    await transporter.sendMail({
      from: `"Inframe College" <${process.env.MAIL_USER}>`,
      to: process.env.MAIL_ADMIN,
      subject: "New Payment Intent Started",
      html,
    });

    return Response.json({ success: true, message: "Email sent!" });
  } catch (error) {
    console.error("Email error:", error);
    return Response.json({ success: false, message: "Email failed" }, { status: 500 });
  }
}
